name: 'Create Index'
description: 'Creates an index to be used in other tests'

inputs:
  environment:
    description: 'The environment of the index (for Pod-based indexes)'
    required: false
  region:
    description: 'The region of the index'
    required: false
    default: 'us-west-2'
  cloud:
    description: 'The cloud of the index'
    required: false
    default: 'aws'
  name_prefix:
    description: 'The prefix of the index name'
    required: false
    default: 'index-name'
  dimension:
    description: 'The dimension of the index'
    required: false
    default: '384'
  metric:
    description: 'The metric of the index'
    required: false
    default: 'cosine'
  PINECONE_API_KEY:
    description: 'The Pinecone API key'
    required: true

outputs:
  index_name:
    description: 'The name of the index, including randomized suffix'
    value: ${{ steps.create-index.outputs.index_name }}
  index_host:
    description: 'The host of the index, including randomized suffix'
    value: ${{ steps.create-index.outputs.index_host }}

runs:
  using: 'composite'
  steps:
    - name: Create index
      id: create-index
      shell: bash
      run: python3 tests/scripts/create_index.py
      env:
        PINECONE_API_KEY: ${{ inputs.PINECONE_API_KEY }}
        NAME_PREFIX: ${{ inputs.name_prefix }}
        ENVIRONMENT: ${{ inputs.environment }}
        REGION: ${{ inputs.region }}
        CLOUD: ${{ inputs.cloud }}
        DIMENSION: ${{ inputs.dimension }}
        METRIC: ${{ inputs.metric }}